config/routes.rb
Rails.application.routes.draw do
  resources :days do
    resources :notes
  end
  
  devise_for :users
  root 'days#index'
  devise_scope :user do
    get "/sign_in" => "devise/sessions#new"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  def self.ransackable_attributes(auth_object = nil)
    ["moodrating", "moodword", "moodjournal", "mooddate"]
  end
  def self.ransackable_associations(auth_object = nil)
    []
  end
end

app/models/day.rb
class Day < ApplicationRecord
    belongs_to :user
    has_many :notes
    

    validates :mooddate, uniqueness: { scope: :user_id }, presence: { message: '- You must select a date.' }
    validates :moodjournal, presence: { message: '- Please add some notes for your future self.' }
    validates :moodword, presence: { message: '- Please add a single word describing your day.' }
    validates :moodrating, 
                numericality: { 
                    only_integer: true, 
                    less_than_or_equal_to: 10, 
                    greater_than_or_equal_to: 0
                },
                presence: { message: '- Please select a value.' }


    def self.ransackable_attributes(auth_object = nil)
        ["moodrating", "moodword", "moodjournal", "mooddate", "isbookmarked"]
    end
    def self.ransackable_associations(auth_object = nil)
        []
    end

end

app/models/note.rb
class Note < ApplicationRecord
    belongs_to :day
    validates :content, presence: true

    
end

app/models/user.rb
class User < ApplicationRecord
  has_many :days
  has_many :notes
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :trackable, :omniauthable

  has_many :days
  has_many :notes, through: :days
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    before_action :set_query

    def set_query
        @q = Day.ransack(params[:q])
    end

    def index
        @q = Day.ransack(params[:q])
        @moodresults = @q.result(distinct: true)
    end

    private
    def authenticate_user!
        if user_signed_in?
        root_path
        else
        render 'home/index', notice: "Please Login to view that page!"
        end
    end
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_action :authenticate_user!
  before_action :set_day, only: %i[ show edit update destroy ]

  def nil.split *args
    nil # splitting of nil, in any imaginable way, can only result again in nil
  end
  
  def index
    @days = current_user.days

    if params[:days_between]
      start_split = params[:days_between].split(" - ").first
    @starts = Date.strptime(start_split, "%m/%d/%Y")
      end_split = params[:days_between].split(" - ").second
    @ends = Date.strptime(end_split, "%m/%d/%Y")
    else
    end
    
    @moodrating = Day.group(:moodrating)

    @q = current_user.days.ransack(params[:q])
    @moodresults = @q.result(distinct: true)
  end

  def show
  end

  def new

    @day = current_user.days.new

  end

  def edit
  end

  def create

    @day = current_user.days.new(day_params)
    respond_to do |format|
      if @day.save
        format.html { redirect_to day_url(@day), notice: "You've added a day" }
        format.json { render :show, status: :created, location: @day }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @day.update(day_params)
        format.html { redirect_to days_path, notice: "Day updated" }
        format.json { render :show, status: :ok, location: @day }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @day.destroy
    respond_to do |format|
      format.html { redirect_to days_url, notice: "Day deleted" }
      format.json { head :no_content }
    end
  end

  
  private

    def set_day
      @day = current_user.days.find(params[:id])
    end

    def day_params
      params.require(:day).permit(:mooddate, :moodrating, :moodjournal, :moodword, :isbookmarked)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController 
  def index
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_day

    def create
      @note = @day.notes.create(note_params)
      respond_to do |format|
        if @note.save
          format.html { redirect_to day_url(@day), notice: "Note created" }
          format.json { render :show, status: :created, location: @day }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @note.errors, status: :unprocessable_entity }
        end
      end
    end

    def edit
        @note = Note.find(params[:id])
    end
    
    def update
        @note = Note.find(params[:id])
        respond_to do |format|
            if @note.update(note_params)
              format.html { redirect_to day_url(@day), notice: "Note updated" }
              format.json { render :show, status: :ok, location: @day }
            else
              format.html { render :edit, status: :unprocessable_entity }
              format.json { render json: @note.errors, status: :unprocessable_entity }
            end
        end
    end    

    def destroy
        @note = Note.find(params[:id])
        @note.destroy

        respond_to do |format|
            format.html { redirect_to day_url, notice: "Note deleted" }
            format.json { head :no_content }
        end
    end

    private

    def note_params
      params.require(:note).permit(:content)
    end

    def set_day
        @day = Day.find(params[:day_id])
    end    

end
  

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @days = current_user.days
    @q = current_user.days.ransack(params[:q])
    @moodresults = @q.result(distinct: true)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/days/_columnchart.html.erb
<%= column_chart current_user.days.group_by_day(:mooddate, current: true).sum(:moodrating), min: 0, max: 10, colors: ["#ff3131"] %>

app/views/days/_day.html.erb
<div id="<%= dom_id day %>" class = " d day">
  
  <p>
    <div class="daydate"><strong>Date</strong></div>
    <%= form_for day do |f| %>
    <div style="display: flex;">
    <div class="daydate"><%= day.mooddate %></div>
    <div class="bookmark"><%= f.check_box :isbookmarked, checked_value: :true, unchecked_value: :false, onchange: "this.form.submit();", :title => "Bookmark"  %></div>
    <% end %>
    </div>
  </p>

  <p>
    <div class="dayl"><strong>Rating from 0 - 10</strong></div>
    <div class="dayl"><%= day.moodrating %></div>
  </p>

 <p>
    <div class="dayl"><strong>One Word Description</strong></div>
   <div class="dayl"> <%= day.moodword %></div>
  </p>

  <p>
    <div class="dayl"><strong>Description</strong></div>
    <div class="dayl"><%= day.moodjournal %></div>
  </p>

</div>

app/views/days/_form.html.erb
<%= form_with(model: day) do |form| %>
  <% if day.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(day.errors.count, "error") %> prohibited this day from being saved:</h2>

      <ul>
        <% day.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form">
    <%= form.label :mooddate, "Date: "%>
  </div>

  <div class="form">
    <%= form.date_field :mooddate, class: "d" %>
  </div>
  <div class="form">
    <%= form.label :moodrating, "Rating from 0 - 10: "%>
  </div>
  
  <div class="form">
      <% 0.upto(10) do |i| %>
      <%= form.radio_button(:moodrating, i) %>
      <%= form.label :moodrating,  :value => i%>
      <% end %>
  </div>

  <div class="form">
    <%= form.label :moodjournal, "Describe your day: "%>
  </div>

  <div class="form">
    <%= form.text_area :moodjournal, class: "d" %>
  </div>

  <div class="form">
    <%= form.label :moodword, "Describe your day in one word: "%>
  </div>

  <div class="form">
    <%= form.text_field :moodword, class: "d" %>
  </div>

  <div class="form">
    <%= form.label :isbookmarked, "Bookmark? "%>
  </div>

  <div class="form">
  <%= form.check_box :isbookmarked, checked_value: :true, unchecked_value: :false %>
  </div>
  
  <div class="form">
    <%= form.submit class: "button btn-primary", class: "d" %>
  </div>

<% end %>

app/views/days/_linechart.html.erb
  <%= line_chart current_user.days.group_by_day(:mooddate, default_value: "missing")
      .sum(:moodrating), 
      library: { spanGaps: true }, min: 0, max: 10 %>

app/views/days/_linechartcustom.html.erb
<%= line_chart current_user.days.group_by_day(:mooddate, default_value: "missing", range: @starts..@ends, expand_range: true).sum(:moodrating), library: {spanGaps: true}, min: 0, max: 10 %>

app/views/days/_piechart.html.erb
<% data = current_user.days.group(:moodrating).count %>
<% mood_colors = {10 => '#d9ffcc', 9 => '#b4ff99', 8 => '#8eff66', 7 => '#7bff4c', 6 => '#43ff00', 5 => '#36cc00', 4 => '#289900', 3 => '#1b6600', 2 => '#0d3300', 1 => '#112f06', 0 => '##000000'} %>
<% colors = [] %>
<% data.each do |moodrating, _|%>
  <%  colors << mood_colors[moodrating] %>
<% end %>

<%= pie_chart data, colors: colors %>

app/views/days/edit.html.erb
<div><%= render "form", day: @day %></div>

<br>

<div>
  <%= link_to "Show this day", @day %> |
  <%= link_to "Back to days", days_path %>
</div>

app/views/days/index.html.erb
<script src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js" type="text/javascript"></script>
<script src="https://cdn.jsdelivr.net/gh/alumuko/vanilla-datetimerange-picker@latest/dist/vanilla-datetimerange-picker.js"></script>

<head>
<%= javascript_importmap_tags %>
</head>

<p style="color: green"><%= notice %></p>

<pre class="d" id="t1">
    __  ___                ________                __            
   /  |/  /___  ____  ____/ /_  __/________ ______/ /_____  _____
  / /|_/ / __ \/ __ \/ __  / / / / ___/ __ `/ ___/ //_/ _ \/ ___/
 / /  / / /_/ / /_/ / /_/ / / / / /  / /_/ / /__/ ,< /  __/ /    
/_/  /_/\____/\____/\__,_/ /_/ /_/   \__,_/\___/_/|_|\___/_/                                                          
</pre>

<body id="body">

  <button type='button' class= "backbutton" onclick="location.href='<%= new_day_path() %>';">Create new daily entry</button> 

  <div id="piechartbutton" class="leftshift1" style="margin-bottom: 1%;"><button onclick="switchpiechart()">See pie chart</button></div>
  <div id="linechartbutton" class="hidden leftshift1" style="margin-bottom: 1%;"><button onclick="switchlinechart()">See line chart</button></div>
  <div id="columnchartbutton" class="hidden leftshift1" style="margin-bottom: 1%;"><button onclick="switchcolumnchart()">See column chart</button></div>

  <div id="linechartbuttons">
    <div style="display: flex; margin-left: 2%;" >
      <div class="leftshift1"><button id="linechartbuttonA" class="buttonselect" onclick="switchlinechartall()">All</button></div>
      <div class="leftshift1"><button id="linechartbuttonC" onclick="switchcustom()">Custom range</button></div>
      <div class="leftshift1 hidden" id="calendersearchbutton">
        <%= form_with url: days_path, method: :get do |form| %>
          <%= form.text_field :days_between, value: params[:days_between], class: "d", data: {controller: "daterangepicker"} %>
          <%= form.submit "search", class: "d" %>
        <% end %>
      </div>
    </div>
  </div>

    <div id="linechart">
        <%= render 'days/linechart' %>
    </div>

      <div id="linechartcustom" class="hidden">
        <%= render 'days/linechartcustom'%>    
      </div>

    <div id="piechart" class="hidden">
        <%= render 'days/piechart'%>    
    </div>

    <div id="columnchart" class="hidden">
        <%= render 'days/columnchart'%>    
    </div>



  <div style="display: flex;">
    <div class="leftshift1"><button id="allinfobutton" class="buttonselect" onclick="switchall()">All</button></div>
    <div class="leftshift1"><button id="ratingsbutton" onclick="switchmoodrating()">Ratings</button></div>
    <div class="leftshift1"><button id="moodwordsbutton" onclick="switchmoodword()">Mood-Words</button></div>
    <div class="leftshift1"><button id="descriptionsbutton" onclick="switchmoodjournal()">Descriptions</button></div>  
  </div>

  <div class="leftshift1" id="searchall"><%= render 'search/formall'%></div>

  <div  class="leftshift1 hidden" id="searchmoodrating"><%= render 'search/formmoodrating'%></div>

  <div  class="leftshift1 hidden" id="searchmoodword"><%= render 'search/formmoodword'%></div>

  <div  class="leftshift1 hidden" id="searchmoodjournal"><%= render 'search/formmoodjournal'%></div>

    <p class="d" id="footer"></p>
  
  </body>

<script>
</script>

app/views/days/new.html.erb
<div><%= render "form", day: @day %></div>

<br>

<div>
  <%= link_to "Back to days", days_path %>
</div>

app/views/days/show.html.erb
<p style="color: green"><%= notice %></p>

<div class= "daydetails2">
  <% if current_user %>
    <%= render current_user.days %>
  <% end %>
</div>

<div class= "leftshift1">
  <button type='button' onclick="location.href='<%= edit_day_path(@day) %>';">Edit</button> 
  <%= button_to "Delete", @day, method: :delete, data: { turbo_confirm: "Are you sure?"} %>
</div>

<div class="d" id="notes">
  <div style="margin-bottom: 2%; margin-top: 5%;"><strong>Notes:</strong></div>

  <% @day.notes.each do |note| %>
    <div class= "notedetails">
      <strong><%= note.created_at.to_date %></strong>
      <div class= "block"> <%= note.content %> </div>
      <div class= "notesbuttons">
  <button type='button' onclick="location.href='<%= edit_day_note_path(@day, note) %>';">Edit</button> 
      <%= button_to "Delete", [@day, note], method: :delete, data: { turbo_confirm: "Are you sure?"} %>
      </div>
    </div>
  <% end %>

  <div class="leftshift1"><%= render partial: "notes/form", locals: {note: @day.notes.new} %></div>

</div>

<div class= backbutton><%= link_to "Back to days", days_path %></div>

app/views/notes/_form.html.erb
<%= form_for [@day, note] do |f| %>

  <div class="field">
    <%= f.label :content, "Note", class: "d" %>
    <%= f.text_area :content, class: "d" %>
  </div>

  <div class="actions">
    <%= f.submit class: "button btn-primary", class: "d"%>
  </div>
<% end %>

app/views/notes/edit.html.erb
<%= render partial: "form", locals: {note: @note} %>

app/views/search/_formall.html.erb
<div style="display: flex;">
    <div>
    <%= search_form_for(@q, url: days_path, method: :get) do |form| %>
        <%= form.search_field :moodword_or_moodrating_or_mooddate_or_moodjournal_eq, class: "d", placeholder: "Search..." %>
        <%= form.submit "Search!", class: "d" %>
    <% end %>
    </div>    

    <div>
    <%= search_form_for(@q, url: days_path, method: :get) do |form| %>
        <div class="hidden"><%= form.search_field :isbookmarked_eq, value: true %></div>
        <div style="margin-left: 6%;"><%= form.submit "Bookmarks", class: "submitbutton" %></div>
    <% end %> 
    </div>    

    <div style="margin-left: 1%;">
    <%= search_form_for(@q, url: days_path, method: :get) do |form| %>
        <div class="hidden"><%= form.search_field :moodword_or_moodrating_or_mooddate_or_moodjournal_eq %></div>
        <div><%= form.submit "Remove bookmark filter", class: "submitbutton" %></div>
    <% end %>
    </div> 
</div>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

<body style="background-color:black;">

<div>
<div class="d"><%= pluralize(@moodresults.count, "Result") %></div>



<div class="d container mt-4" style="background-color:#212529;">
    <table class="table table-dark table-hover ">
        <thead>
            <tr>
            <th><%= sort_link(@q, :mooddate, "Date", default_order: :mooddate) %></th>
            <th><%= sort_link(@q, :moodword, "Word") %></th>
            <th><%= sort_link(@q, :moodjournal, "Description") %></th>
            <th><%= sort_link(@q, :moodrating, "Rating") %></th>
            </tr>
        </thead>  
    <tbody id="tableall">
        <% @moodresults.each do |d| %>
        <tr>
            <%= form_for d do |f| %>
            <td style="display: flex;">
            <%= link_to d.mooddate, d %>
            <div style="background-color:#212529;" class="bookmark" >
            <%= f.check_box :isbookmarked, checked_value: :true, unchecked_value: :false, onchange: "this.form.submit();", :title => "Bookmark" %>
            </div>
            <% end %>
            <div class="tbb"><button type='button' onclick="location.href='<%= edit_day_path(d) %>';">Edit</button></div>
            <div class="tbb"><%= button_to "Delete", d, method: :delete, data: { turbo_confirm: "Are you sure?"} %></div>
            </td>
            <td><%= d.moodword %></td>
            <td><%= d.moodjournal.truncate_words(10) %></td>
            <td><%= d.moodrating %></td>
        </tr>
        <% end %>
    </tbody>
    </table>
</div>


</div>

</body>

app/views/search/_formmoodjournal.html.erb
<div style="display: flex;">

    <%= search_form_for(@q, url: days_path, method: :get) do |form| %>
        <%= form.search_field :moodjournal_i_cont_all, placeholder: "Search...", class: "d" %>
        <%= form.submit "Search Descriptions!", class: "d" %>
    <% end %>    

    <div>
    <%= search_form_for(@q, url: days_path, method: :get) do |form| %>
        <div class="hidden"><%= form.search_field :isbookmarked_eq, value: true %></div>
        <div style="margin-left: 6%;"><%= form.submit "Bookmarks", class: "submitbutton" %></div>
    <% end %> 
    </div>    

    <div style="margin-left: 1%;">
    <%= search_form_for(@q, url: days_path, method: :get) do |form| %>
        <div class="hidden"><%= form.search_field :moodword_or_moodrating_or_mooddate_or_moodjournal_eq %></div>
        <div><%= form.submit "Remove bookmark filter", class: "submitbutton" %></div>
    <% end %>
    </div> 

</div>




<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

<body style="background-color:black;">

<div>
<div class="d"><%= pluralize(@moodresults.count, "Result") %></div>



<div class="d container mt-4" style="background-color:#212529;">
    <table class="table table-dark table-hover">
        <thead>
            <tr>
            <th><%= sort_link(@q, :mooddate, "Date", default_order: :mooddate) %></th>
            <th><%= sort_link(@q, :moodjournal, "Description") %></th>
            </tr>
        </thead>  
    <tbody>
        <% @moodresults.each do |d| %>
        <tr>
            <%= form_for d do |f| %>
            <td style="display: flex;">
            <%= link_to d.mooddate, d %>
            <div style="background-color:#212529;" class="bookmark" >
            <%= f.check_box :isbookmarked, checked_value: :true, unchecked_value: :false, onchange: "this.form.submit();", :title => "Bookmark" %>
            </div>
            <% end %>
            <div><button type='button' onclick="location.href='<%= edit_day_path(d) %>';">Edit</button></div>
            <div><%= button_to "Delete", d, method: :delete, data: { turbo_confirm: "Are you sure?"} %></div>
            </td>            
            <td><%= d.moodjournal.truncate_words(50) %></td>
        </tr>
        <% end %>
    </tbody>
    </table>
</div>


</div>

</body>

app/views/search/_formmoodrating.html.erb
<div style="display: flex;">

    <%= search_form_for(@q, url: days_path, method: :get) do |form| %>
        <%= form.search_field :moodrating_eq, placeholder: "Search...", class:"d" %>
        <%= form.submit "Search Ratings!", class:"d" %>
    <% end %>    

    <div>
    <%= search_form_for(@q, url: days_path, method: :get) do |form| %>
        <div class="hidden"><%= form.search_field :isbookmarked_eq, value: true %></div>
        <div style="margin-left: 6%;"><%= form.submit "Bookmarks", class: "submitbutton" %></div>
    <% end %> 
    </div>    

    <div style="margin-left: 1%;">
    <%= search_form_for(@q, url: days_path, method: :get) do |form| %>
        <div class="hidden"><%= form.search_field :moodword_or_moodrating_or_mooddate_or_moodjournal_eq %></div>
        <div><%= form.submit "Remove bookmark filter", class: "submitbutton" %></div>
    <% end %>
    </div> 

</div>




<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

<body style="background-color:black;">

<div>
<div class="d"><%= pluralize(@moodresults.count, "Result") %></h3></div>



<div class="d container mt-4" style="background-color:#212529;">
    <table class="table table-dark table-hover">
        <thead>
            <tr>
            <th><%= sort_link(@q, :mooddate, "Date", default_order: :mooddate) %></th>
            <th><%= sort_link(@q, :moodrating, "Rating") %></th>
            </tr>
        </thead>  
    <tbody>
        <% @moodresults.each do |d| %>
        <tr>
            <%= form_for d do |f| %>
            <td style="display: flex;">
            <%= link_to d.mooddate, d %>
            <div style="background-color:#212529;" class="bookmark" >
            <%= f.check_box :isbookmarked, checked_value: :true, unchecked_value: :false, onchange: "this.form.submit();", :title => "Bookmark" %>
            </div>
            <% end %>
            <div class="tbb"><button type='button' onclick="location.href='<%= edit_day_path(d) %>';">Edit</button></div>
            <div class="tbb"><%= button_to "Delete", d, method: :delete, data: { turbo_confirm: "Are you sure?"} %></div>
            </td>            
            <td><%= d.moodrating %></td>
        </tr>
        <% end %>
    </tbody>
    </table>
</div>


</div>

</body>

app/views/search/_formmoodword.html.erb
<div style="display: flex;">

    <%= search_form_for(@q, url: days_path, method: :get) do |form| %>
        <%= form.search_field :moodword_i_cont_all, placeholder: "Search...", class:"d" %>
        <%= form.submit "Search Mood-Words!", class:"d" %>
    <% end %>    

    <div>
    <%= search_form_for(@q, url: days_path, method: :get) do |form| %>
        <div class="hidden"><%= form.search_field :isbookmarked_eq, value: true %></div>
        <div style="margin-left: 6%;"><%= form.submit "Bookmarks", class: "submitbutton" %></div>
    <% end %> 
    </div>    

    <div style="margin-left: 1%;">
    <%= search_form_for(@q, url: days_path, method: :get) do |form| %>
        <div class="hidden"><%= form.search_field :moodword_or_moodrating_or_mooddate_or_moodjournal_eq %></div>
        <div><%= form.submit "Remove bookmark filter", class: "submitbutton" %></div>
    <% end %>
    </div> 

</div>




<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

<body style="background-color:black;">


<div>
<div class="d"><%= pluralize(@moodresults.count, "Result") %></h3></div>



<div class="d container mt-4" style="background-color:#212529;">
    <table class="table table-dark table-hover">
        <thead>
            <tr>
            <th><%= sort_link(@q, :mooddate, "Date", default_order: :mooddate) %></th>
            <th><%= sort_link(@q, :moodword, "Word") %></th>
            </tr>
        </thead>  
    <tbody>
        <% @moodresults.each do |d| %>
        <tr>
            <%= form_for d do |f| %>
            <td style="display: flex;">
            <%= link_to d.mooddate, d %>
            <div style="background-color:#212529;" class="bookmark" >
            <%= f.check_box :isbookmarked, checked_value: :true, unchecked_value: :false, onchange: "this.form.submit();", :title => "Bookmark" %>
            </div>
            <% end %>
            <div class="tbb"><button type='button' onclick="location.href='<%= edit_day_path(d) %>';">Edit</button></div>
            <div class="tbb"><%= button_to "Delete", d, method: :delete, data: { turbo_confirm: "Are you sure?"} %></div>
            </td>            
            <td><%= d.moodword %></td>
        </tr>
        <% end %>
    </tbody>
    </table>
</div>


</div>

</body>

app/views/shared/_alert.html.erb
<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>